# Generated by Django 5.0.2 on 2024-04-19 22:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0003_pedido_delete_pedidoitem'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.today)),
                ('data_atualizacao', models.DateTimeField(default=datetime.datetime.today)),
                ('quantidade', models.IntegerField()),
                ('comentario', models.CharField(max_length=128)),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido')),
                ('id_produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
    ]
