# Generated by Django 5.0.2 on 2024-04-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='comentario',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
