# Generated by Django 5.0.2 on 2024-04-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoItem', '0002_alter_pedidoitem_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='quantidade',
            field=models.IntegerField(null=True),
        ),
    ]
