# Generated by Django 5.0.2 on 2024-04-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cnpj', models.CharField(max_length=14)),
                ('razao_social', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=80)),
                ('sexo', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=11)),
                ('logradouro', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=6)),
                ('bairro', models.CharField(max_length=30)),
                ('complemento', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
