# Generated by Django 5.0.2 on 2024-04-19 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.AddField(
            model_name='administrador',
            name='data_atualizacao',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='administrador',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
