# Generated by Django 5.0.2 on 2024-04-19 22:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_delete_empresa_delete_vendedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cnpj', models.CharField(max_length=14)),
                ('razao_social', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.today)),
                ('data_atualizacao', models.DateTimeField(default=datetime.datetime.today)),
                ('nome', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=80)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=2)),
                ('telefone', models.CharField(max_length=11)),
                ('logradouro', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=6)),
                ('bairro', models.CharField(max_length=30)),
                ('complemento', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=2)),
                ('pais', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.empresa')),
            ],
        ),
    ]
