# Generated by Django 5.0.2 on 2024-04-19 22:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedidoitem_id_produto'),
        ('usuario', '0003_empresa_cliente_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.today)),
                ('data_atualizacao', models.DateTimeField(default=datetime.datetime.today)),
                ('valor_total', models.FloatField()),
                ('forma_pagamento', models.CharField(max_length=15)),
                ('data_prevista_entrega', models.DateTimeField()),
                ('data_entrega', models.DateTimeField()),
                ('logradouro', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=6)),
                ('bairro', models.CharField(max_length=30)),
                ('complemento', models.CharField(max_length=30)),
                ('valor_promocional', models.FloatField(null=True)),
                ('status', models.CharField(max_length=15)),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
