# Generated by Django 5.0.2 on 2024-04-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_delete_pedidoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='bairro',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='complemento',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data_prevista_entrega',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Crédito', 'Crédito'), ('Débito', 'Débito'), ('PIX', 'PIX')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='logradouro',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Em andamento', 'Em andamento'), ('Cancelado', 'Cancelado'), ('Concluido', 'Concluido')], max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.FloatField(default=0),
        ),
    ]
